export const USER_SIGNUP_HEADING="SignUp "
export const TRAINER_SIGNUP_HEADING="Trainer Signup"
export const ADDWORKOUTS="Add Workouts"
export const MANAGEWORKOUTS="Manage Workouts"
export const COURSE_CONTENTS="Course Contetnts"